/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'GreyVectorFile.o'
*/

struct _GB_DecoderRec;
struct _GB_DataRec;
struct _GB_LibraryRec;
struct _GB_LoaderRec;
struct _RTC_vardesc;

/* 1 */
enum GB_DataFormat : __int32
{
};

/* 2 */
struct _GB_StreamRec
{
  void *handler;
  int (__cdecl *read)(void *, unsigned __int8 *, int);
  int (__cdecl *write)(void *, unsigned __int8 *, int);
  int (__cdecl *seek)(void *, int);
  void (__cdecl *close)(void *);
  int size;
  char *pfilename;
};

/* 3 */
struct tagGREYVECTORFILEHEADER
{
  char gbfTag[4];
  unsigned int gbfSize;
};

/* 4 */
struct _GB_MemoryRec
{
  void *(__cdecl *malloc)(int);
  void *(__cdecl *realloc)(void *, int);
  void (__cdecl *free)(void *);
};

/* 5 */
struct _GB_FormatRec
{
  _GB_FormatRec *next;
  char tag[4];
  char (__cdecl *probe)(_GB_StreamRec *);
  _GB_DecoderRec *(__cdecl *decodernew)(_GB_LoaderRec *, _GB_StreamRec *);
};

/* 6 */
struct _GB_DecoderRec
{
  int (__cdecl *setparam)(_GB_DecoderRec *, void *);
  int (__cdecl *getcount)(_GB_DecoderRec *);
  __int16 (__cdecl *getwidth)(_GB_DecoderRec *, unsigned int, __int16);
  int (__cdecl *decode)(_GB_DecoderRec *, unsigned int, _GB_DataRec *, __int16);
  void (__cdecl *done)(_GB_DecoderRec *);
};

/* 9 */
struct _GB_LoaderRec
{
  _GB_LibraryRec *gbLibrary;
  _GB_MemoryRec *gbMem;
  _GB_StreamRec *gbStream;
  _GB_DecoderRec *gbDecoder;
};

/* 19 */
typedef __int16 GB_INT16;

/* 7 */
struct _GB_DataRec
{
  GB_DataFormat format;
  GB_INT16 width;
  void *data;
};

/* 8 */
struct _GB_LibraryRec
{
  _GB_MemoryRec *gbMem;
  _GB_FormatRec *gbFormatHeader;
};

/* 10 */
struct _GUID
{
  unsigned int Data1;
  unsigned __int16 Data2;
  unsigned __int16 Data3;
  unsigned __int8 Data4[8];
};

/* 11 */
typedef struct _GUID GUID;

/* 12 */
struct _RTC_framedesc
{
  int varCount;
  _RTC_vardesc *variables;
};

/* 13 */
struct _RTC_vardesc
{
  int addr;
  int size;
  char *name;
};

/* 14 */
typedef void *GBHANDLE;

/* 15 */
typedef char GB_BOOL;

/* 16 */
typedef unsigned __int8 GB_BYTE;

/* 17 */
typedef unsigned __int16 GB_UINT16;

/* 18 */
typedef unsigned int GB_UINT32;

/* 20 */
typedef int GB_INT32;

/* 21 */
typedef GB_INT16 GB_Pos;

/* 22 */
typedef char GB_CHAR;

/* 23 */
enum $4FBDB95B01ADE9C0845B06BB7E84947D
{
  GB_FORMAT_NONE = 0x0,
  GB_FORMAT_BITMAP = 0x1,
  GB_FORMAT_OUTLINE = 0x2,
  GB_FROMAT_MAX = 0x3,
};

/* 24 */
typedef struct _GB_DataRec GB_DataRec;

/* 25 */
typedef struct _GB_DataRec *GB_Data;

/* 26 */
struct _GB_BitmapRec
{
  GB_INT16 width;
  GB_INT16 height;
  GB_INT16 pitch;
  GB_INT16 bitcount;
  GB_BYTE *buffer;
};

/* 27 */
typedef struct _GB_BitmapRec GB_BitmapRec;

/* 28 */
typedef struct _GB_BitmapRec *GB_Bitmap;

/* 29 */
struct _GB_PointRec
{
  GB_Pos x;
  GB_Pos y;
};

/* 30 */
typedef struct _GB_PointRec GB_PointRec;

/* 31 */
typedef struct _GB_PointRec *GB_Point;

/* 32 */
struct _GB_OutlineRec
{
  GB_INT16 n_contours;
  GB_INT16 n_points;
  GB_Point points;
  GB_BYTE *tags;
  GB_INT16 *contours;
};

/* 33 */
typedef struct _GB_OutlineRec GB_OutlineRec;

/* 34 */
typedef struct _GB_OutlineRec *GB_Outline;

/* 35 */
struct _GB_GbfParamRec::$C51D81097B6B44D5A2394C13069B1F7F
{
  GB_INT32 nCacheItem;
};

/* 36 */
struct _GB_GbfParamRec::$2A049B20BA6337A0CE2E26A2DD6479D7
{
  GB_INT16 nHeight;
  GB_INT16 nBitCount;
  GB_BOOL bCompress;
};

/* 37 */
union _GB_GbfParamRec
{
  struct _GB_GbfParamRec::$C51D81097B6B44D5A2394C13069B1F7F decoder;
  struct _GB_GbfParamRec::$2A049B20BA6337A0CE2E26A2DD6479D7 encoder;
};

/* 38 */
typedef union _GB_GbfParamRec GB_GbfParamRec;

/* 39 */
typedef union _GB_GbfParamRec *GB_GbfParam;

/* 40 */
struct _GB_TtfParamRec::$0D631B65C53F6F99B1D35DE2FE31BC10
{
  GB_INT32 unused;
};

/* 41 */
union _GB_TtfParamRec
{
  struct _GB_TtfParamRec::$0D631B65C53F6F99B1D35DE2FE31BC10 decoder;
  struct _GB_TtfParamRec::$0D631B65C53F6F99B1D35DE2FE31BC10 encoder;
};

/* 42 */
typedef union _GB_TtfParamRec GB_TtfParamRec;

/* 43 */
typedef union _GB_TtfParamRec *GB_TtfParam;

/* 44 */
struct _GB_GvfParamRec::$C51D81097B6B44D5A2394C13069B1F7F
{
  GB_INT32 nCacheItem;
};

/* 45 */
struct _GB_GvfParamRec::$6E1CB9E872F49D59AFFEE3093526D01C
{
  GB_INT16 nHeight;
};

/* 46 */
union _GB_GvfParamRec
{
  struct _GB_GvfParamRec::$C51D81097B6B44D5A2394C13069B1F7F decoder;
  struct _GB_GvfParamRec::$6E1CB9E872F49D59AFFEE3093526D01C encoder;
};

/* 47 */
typedef union _GB_GvfParamRec GB_GvfParamRec;

/* 48 */
typedef union _GB_GvfParamRec *GB_GvfParam;

