/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

bool __cdecl GreyVectorFile_Probe(_GB_StreamRec *stream);
_GB_FormatRec *__cdecl GreyVectorFile_Format_New(_GB_LibraryRec *library); // idb


//----- (00000000) --------------------------------------------------------
bool __cdecl GreyVectorFile_Probe(_GB_StreamRec *stream)
{
  tagGREYVECTORFILEHEADER fileHeader; // [esp+4h] [ebp-10h] BYREF
  int v3; // [esp+Ch] [ebp-8h]
  int v4; // [esp+10h] [ebp-4h]

  *(_DWORD *)fileHeader.gbfTag = -858993460;
  fileHeader.gbfSize = -858993460;
  v3 = -858993460;
  v4 = -858993460;
  GreyBit_Stream_Seek(stream, 0);
  return GreyBit_Stream_Read(stream, &fileHeader, 8) == 8
      && fileHeader.gbfTag[0] == 103
      && fileHeader.gbfTag[1] == 118
      && fileHeader.gbfTag[2] == 116
      && fileHeader.gbfTag[3] == 102;
}
// 130: using guessed type int __cdecl GreyBit_Stream_Read(_DWORD, _DWORD, _DWORD);
// 134: using guessed type int __cdecl GreyBit_Stream_Seek(_DWORD, _DWORD);

//----- (000000C0) --------------------------------------------------------
_GB_FormatRec *__cdecl GreyVectorFile_Format_New(_GB_LibraryRec *library)
{
  _GB_FormatRec *format; // [esp+0h] [ebp-4h]

  format = (_GB_FormatRec *)GreyBit_Malloc(library->gbMem, 16);
  if ( format )
  {
    format->next = 0;
    format->tag[0] = 103;
    format->tag[1] = 118;
    format->tag[2] = 102;
    format->probe = (char (__cdecl *)(_GB_StreamRec *))GreyVectorFile_Probe;
    format->decodernew = (_GB_DecoderRec *(__cdecl *)(_GB_LoaderRec *, _GB_StreamRec *))&GreyVectorFile_Decoder_New;
  }
  return format;
}
// 154: using guessed type int __cdecl GreyBit_Malloc(_DWORD, _DWORD);

// nfuncs=9 queued=2 decompiled=2 lumina nreq=0 worse=0 better=0
// ALL OK, 2 function(s) have been successfully decompiled
